name: "classifier_7"

dataset:
  name: "eight_angles.csv"
  splits: [0.7, 0.2, 0.1]
  batch_size: 128
  seed: 42

hyperparameters:
  epochs: 50
  learning_rate: 0.01
  optimizer: "adam"
  criterion: "bce"
  seed: 42

model:
  input_dim: 151
  hidden_dims: [400, 200]
  output_dim: 8
  use_batch_norm: True
  dropout: 0.2
  output_activation: "softmax"
