name: "classifier_4"

dataset:
  name: "eight_angles_middle.csv"
  splits: [0.7, 0.2, 0.1]
  seed: 42

hyperparameters:
  epochs: 300
  learning_rate: 0.001
  optimizer: "adam"
  criterion: "bce"
  seed: 42

model:
  input_dim: 110
  hidden_dims: [400, 200]
  output_dim: 8
  use_batch_norm: True
  dropout: 0.2
  output_activation: "softmax"
