name: "classifier_6"

dataset:
  name: "eight_angles_1.csv"
  splits: [0.7, 0.2, 0.1]
  seed: 42

hyperparameters:
  epochs: 70
  learning_rate: 0.001
  optimizer: "adam"
  criterion: "bce"
  seed: 42

model:
  input_dim: 71
  hidden_dims: [200, 100]
  output_dim: 8
  use_batch_norm: True
  dropout: 0.2
  output_activation: "softmax"
