name: "classifier_accuracy"

dataset:
  name: "accuracy.csv"
  splits: [0.7, 0.2, 0.1]
  batch_size: 128
  seed: 42

hyperparameters:
  epochs: 50
  learning_rate: 0.005
  optimizer: "adam"
  criterion: "mse"
  seed: 42

model:
  input_dim: 33
  hidden_dims: [200, 100]
  output_dim: 1
  use_batch_norm: True
  dropout: 0.2
  output_activation: "softmax"
